### ISSUE TITLE
Unable to run Grunt Serve or Deploy

### ISSUE THREAD

**Issue by artpylon** [ga-wdi-boston/portfolio-template#1]
I believe I've successfully setup my local and remote repo for my portfolio, but I'm unable to run grunt commands, grunt serve or grunt deploy. I ran NPM Install inside the repo. 

Do I need grunt?

Grunt serve returns:
$ grunt serve
grunt-cli: The grunt command line interface (v1.2.0)

Fatal error: Unable to find local grunt.

If you're seeing this message, grunt hasn't been installed locally to
your project. For more information about installing and configuring grunt,
please see the Getting Started guide:

http://gruntjs.com/getting-started

Grunt Deploy returns:

$ grunt deploy
grunt-cli: The grunt command line interface (v1.2.0)

Fatal error: Unable to find local grunt.

If you're seeing this message, grunt hasn't been installed locally to
your project. For more information about installing and configuring grunt,
please see the Getting Started guide:

**Comment by payne-chris-r** [comment]
That's expected. There's no webpack. There's no grunt.
