### ISSUE TITLE
Bootstrap navbar does not appear to pick up styling

### ISSUE THREAD

**Issue by lisawilliams** [ga-wdi-boston/portfolio-template#2]
Hi, all: 

I'm getting unexpected behavior when I try to implement a Bootstrap navbar using portfolio-template. Here is the relevant code from index.html: 

```
  <div class = "container">
     <div class ="navbar">
     <ul class="nav">
       <li class="active">
         <a href="#">Home</a>
       </li>
       <li><a href="#">Link</a></li>
       <li><a href="#">Link</a></li>
     </ul>
   </div>
 </div>
```
I got this approach from the [Bootstrap documentation](http://getbootstrap.com/2.3.2/components.html#navbar) for `.navbar`

But I don't get something that looks like the navbar in the documentation out of this -- instead I get this: 

<img width="1280" alt="screen shot 2017-07-07 at 4 11 32 pm" src="https://user-images.githubusercontent.com/809042/27975291-7f298984-632f-11e7-9775-2155a755a2fb.png">

Can you give me some hints about what might be going wrong? Thanks. Oh: [here's my repo](https://github.com/lisawilliams/portfolio) if you'd like to browse.

**Comment by lisawilliams** [comment]
Paging @Jcornmanhomonoff :D

**Comment by cpearce31** [comment]
Take another look at those docs you linked, looks like you're missing a `<div>`

**Comment by lisawilliams** [comment]
ooh thanks Caleb! I will look!

**Comment by lisawilliams** [comment]
Hey! Got it fixed. Thanks, Caleb, for pointing out that I was looking at a version of the docs that didn't match up with my version of Bootstrap. 

Here's the issue on my repo with the resulting code: https://github.com/lisawilliams/portfolio/issues/3
