### ISSUE TITLE
difficulty deploying to gh-pages

### ISSUE THREAD

**Issue by ryanwk** [ga-wdi-boston/portfolio-template#6]
I went into the settings section of my github repo for my portfolio and activated gh-pages.
I have two branches: master & working. 
When I go to https://ryanwk.github.io/portfolio/. I don't see any updated changes that I made to my portfolio. 

Here's a view from my terminal: 
~/wdi/projects 
$ cd portfolio/
~/wdi/projects/portfolio (working)
$ git push origin working
Everything up-to-date
~/wdi/projects/portfolio (working)
$ git push origin master
Everything up-to-date
~/wdi/projects/portfolio (working)
$ git remote -v
origin	git@github.com:ryanwk/portfolio.git (fetch)
origin	git@github.com:ryanwk/portfolio.git (push)
~/wdi/projects/portfolio (working)
$ git status
On branch working
nothing to commit, working tree clean
~/wdi/projects/portfolio (working)
$ git checkout master
Switched to branch 'master'
~/wdi/projects/portfolio (master)
$ git push origin master
Everything up-to-date
~/wdi/projects/portfolio (master)
$ git status
On branch master
nothing to commit, working tree clean
~/wdi/projects/portfolio (master)

Things I've done:
spent hours researching my problem.
I found this resource and this is what I will be trying next: 
https://gist.github.com/chrisjacob/825950, which is a "Setup GitHub Pages "gh-pages" branch as a subfolder within the "master" project on your local checkout - a step-by-step guide".

**Comment by ryanwk** [comment]
so I followed those steps and it's getting messy:

~/wdi/projects/portfolio (master)
$ mkdir master
~/wdi/projects/portfolio (master)
$ ls
CONTRIBUTING.md	grunt		lib		package.json
LICENSE		img		main.css
README.md	index.html	master
STYLE.md	index.js	node_modules
~/wdi/projects/portfolio (master)
$ cd master/
~/wdi/projects/portfolio/master (master)
$ clear

~/wdi/projects/portfolio/master (master)
$ git init
Initialized empty Git repository in /Users/pirakoch/wdi/projects/portfolio/master/.git/
~/wdi/projects/portfolio/master (master)
$ echo "# Master README file" > README.markdown
~/wdi/projects/portfolio/master (master)
$ git add .
~/wdi/projects/portfolio/master (master)
$ git commit -m "Master README added"
[master (root-commit) 7b77238] Master README added
 1 file changed, 1 insertion(+)
 create mode 100644 README.markdown
~/wdi/projects/portfolio/master (master)
$ git remote add origin git@github.com:ryanwk/portfolio.git
~/wdi/projects/portfolio/master (master)
$ git push origin master
To github.com:ryanwk/portfolio.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'git@github.com:ryanwk/portfolio.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
~/wdi/projects/portfolio/master (master)

**Comment by cpearce31** [comment]
When you deployed your game project, you used a Grunt script that took care of all the details for you. Portfolio template doesn't have this, so you have to do it the old fashioned way. Follow the instructions here: https://pages.github.com/. You will need to rename your your repository on Github per the instructions.

**Comment by ryanwk** [comment]
I followed those instructions over the weekend. As a result I've got a repo on github called ryanwk.github.io. I also have a local repo with that name. This was confusing so I just made a local repo called portfolio and a github repo called portfolio then used git remote add to connect my local portfolio to my remote github portfolio repo.

**Comment by cpearce31** [comment]
I'll take a look at this with you on a break or during lunch if you'd like.

**Comment by ryanwk** [comment]
ok thank you!

**Comment by ryanwk** [comment]
problem solved. My repo now uses github.io as it's remote. Do what Caleb said " Follow the instructions here: https://pages.github.com/. " Thank you!
